export const tailwindColorsLight = {
  "background": "var(--color-background)",
  "background-secondary": "var(--color-background-secondary)",
  "background-reversed": "var(--color-background-reversed)",
  "card": "var(--color-card)",
  "card-secondary": "var(--color-card-secondary)",
  "card-reversed": "var(--color-card-reversed)",
  "text-full": "var(--color-text-full)",
  "text-primary": "var(--color-text-primary)",
  "text-secondary": "var(--color-text-secondary)",
  "blue-button": "var(--color-blue-button)",
  "gray-highlight-100": "var(--color-gray-highlight-100)",
  "gray-highlight-200": "var(--color-gray-highlight-200)",
  "gray-highlight-300": "var(--color-gray-highlight-300)",
  "mood-colors-0": "var(--color-mood-colors-0)",
  "mood-colors-1": "var(--color-mood-colors-1)",
  "mood-colors-2": "var(--color-mood-colors-2)",
  "mood-colors-3": "var(--color-mood-colors-3)",
  "mood-colors-4": "var(--color-mood-colors-4)"
};

export const tailwindColorsDark = {
  "background": "var(--color-background)",
  "background-reversed": "var(--color-background-reversed)",
  "background-secondary": "var(--color-background-secondary)",
  "card": "var(--color-card)",
  "card-secondary": "var(--color-card-secondary)",
  "card-reversed": "var(--color-card-reversed)",
  "text-full": "var(--color-text-full)",
  "text-primary": "var(--color-text-primary)",
  "text-secondary": "var(--color-text-secondary)",
  "blue-button": "var(--color-blue-button)",
  "gray-highlight-100": "var(--color-gray-highlight-100)",
  "gray-highlight-200": "var(--color-gray-highlight-200)",
  "gray-highlight-300": "var(--color-gray-highlight-300)",
  "mood-colors-0": "var(--color-mood-colors-0)",
  "mood-colors-1": "var(--color-mood-colors-1)",
  "mood-colors-2": "var(--color-mood-colors-2)",
  "mood-colors-3": "var(--color-mood-colors-3)",
  "mood-colors-4": "var(--color-mood-colors-4)"
};
